const GITHUB_AUTH_TOKEN = "null"
const BOT_NUMBER = "null"
const SESSION_ID = "PRABATH-MD~o6kyDa7Y#XKAIDdU950A5ruINShG5gK4KM5lsTZmn7sDF6OKXOrw"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
